version: v0.0.2
config:
  servos:
    thumb: 2
    index: 3
    index_shift: 4
    middle: 17
    ring: 27
    small: 22
    palm: 10
  words:
    A:
      thumb: 0
      index: 0
      index_shift: 0
      middle: 0
      ring: 0
      small: 0
      palm: 0
