version: v0.0.0
config:
  finger:
    A:
      thumb: 0
      index: 0
      index_shift: 0
      middle: 0
      ring: 0
      small: 0
      palm: 0
  transitions:
    - from: A
      to: B
      animation: 
        - thumb: 0
          index: 0
          index_shift: 0
          middle: 0
          ring: 0
          small: 0
          palm: 0