version: v0.1.0
config:
  servos:
    thumb: { pin: 10 }
    index: 22
    index_shift: 2
    middle: 27
    ring: { pin: 17, inverted: true }
    small: 4
    palm: 6
  words:
    MAX:
      thumb: 180
      index: 180
      index_shift: 180
      middle: 180
      ring: 180
      small: 180
      palm: 180
    MIN:
      thumb: 0
      index: 0
      index_shift: 0
      middle: 0
      ring: 0
      small: 0
      palm: 0
    A:
      thumb: 90
      index: 180
      index_shift: 90
      middle: 180
      ring: 180
      small: 180
      palm: 0
    B:
      thumb: 180
      index: 0
      index_shift: 90
      middle: 0
      ring: 0
      small: 0
      palm: 0
    C:
      thumb: 45
      index: 135
      index_shift: 135
      middle: 135
      ring: 135
      small: 135
      palm: 0
    D:
      thumb: 135
      index: 0
      index_shift: 90
      middle: 135
      ring: 135
      small: 135
      palm: 45
    E:
      thumb: 180
      index: 135
      index_shift: 90
      middle: 135
      ring: 135
      small: 135
      palm: 0
    F:
      thumb: 1
      index: 135
      index_shift: 90
      middle: 0
      ring: 0
      small: 0
      palm: 45
    G:
      thumb: 90
      index: 0
      index_shift: 90
      middle: 180
      ring: 180
      small: 180
      palm: 180
    H:
      thumb: 90
      palm: 180
      index: 0
      index_shift: 20
      middle: 0
      ring: 180
      small: 180
    I:
      thumb: 180
      index: 180
      index_shift: 0
      middle: 180
      ring: 180
      small: 0
      palm: 0
    J:
      thumb: 90
      index: 180
      index_shift: 0
      middle: 180
      ring: 180
      small: 0
      palm: 0
    K:
      thumb: 115
      palm: 180
      index: 0
      # TODO: can we get more realistic index_shift?
      index_shift: 0
      middle: 0
      ring: 180
      small: 180
    L:
      thumb: 45
      index: 0
      index_shift: 0
      palm: 0
      middle: 180
      ring: 180
      small: 180
    M:
      thumb: 180
      index: 180
      index_shift: 0
      middle: 180
      ring: 180
      small: 180
      palm: 10
    N:
      thumb: 135
      index: 145
      index_shift: 0
      middle: 145
      ring: 180
      small: 180
      palm: 10
    Z:
      thumb: 180
      index: 0
      index_shift: 90
      middle: 180
      ring: 180
      small: 180
      palm: 90
    Y:
      thumb: 45
      index: 180
      index_shift: 0
      middle: 180
      ring: 180
      small: 0
      palm: 0
    X:
      thumb: 130
      index: 0
      index_shift: 0
      middle: 180
      ring: 180
      small: 180
      palm: 10
    W:
      thumb: 135
      index: 0
      index_shift: 0
      middle: 0
      ring: 0
      small: 180
      palm: 15
    V:
      thumb: 120
      index: 0
      index_shift: 0
      middle: 0
      ring: 180
      small: 180
      palm: 15
    U:
      thumb: 120
      index: 0
      index_shift: 0
      middle: 0
      ring: 180
      small: 180
      palm: 15
    T:
      thumb: 110
      index: 180
      index_shift: 50
      middle: 180
      ring: 180
      small: 180
      palm: 5
    S:
      thumb: 180
      index: 180
      index_shift: 0
      middle: 180
      ring: 180
      small: 180
      palm: 15
    R:
      thumb: 120
      index: 0
      index_shift: 100
      middle: 0
      ring: 180
      small: 180
      palm: 15
    Q:
      thumb: 100
      index: 0
      index_shift: 0
      middle: 180
      ring: 180
      small: 180
      palm: 0
    P:
      thumb: 100
      index: 0
      index_shift: 0
      middle: 90
      ring: 180
      small: 180
      palm: 5
    O:
      thumb: 120
      index: 90
      index_shift: 0
      middle: 120
      ring: 150
      small: 180
      palm: 180
