name: Compile the LaTeX file

on: [push]

jobs:
    build-latex:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
                  cache: "pip"
            - name: Install pygments
              run: sudo apt-get install python3-pygments
            - name: Compile LaTeX
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: main.tex
                  working_directory: log
                  latexmk_use_xelatex: true
                  latexmk_shell_escape: true
                  args: "-file-line-error -halt-on-error -interaction=nonstopmode"
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: logbook
                  path: log/main.pdf
